In [7]:
import numpy as np

In [1]:
a = []
type(a)

list

In [2]:
x = ()
type(x)

tuple

In [3]:
x = (10)
type(x)

int

In [4]:
x = (10,)  # 튜플 형태를 유지하기 위해 ,를 붙여줌
type(x)

tuple

#### 파일읽기

In [8]:
iris = np.genfromtxt('./dataset/iris.csv', delimiter=',', skip_header=True)
iris[:5]


array([[5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan]])

In [9]:
xarr=iris[:,:-1]
xarr

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
x = xarr[xarr[:,0] > 5.8,:]
x[:5]

array([[7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [6.5, 2.8, 4.6, 1.5],
       [6.3, 3.3, 4.7, 1.6]])

In [11]:
y = xarr[xarr[:,0]<=5.8,:]
y[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [12]:
np.savez('my_iris.npz', my_x=x, my_y=y)

In [13]:
!dir

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: C526-FA05

 C:\workspace\myml 디렉터리

2022-07-14  오후 02:48    <DIR>          .
2022-07-14  오전 10:01    <DIR>          ..
2022-07-14  오전 10:45    <DIR>          .ipynb_checkpoints
2022-07-14  오후 02:48            10,633 01. numpy.ipynb
2022-07-14  오후 02:23    <DIR>          dataset
2022-07-14  오후 02:47             5,302 my_iris.npz
               2개 파일              15,935 바이트
               4개 디렉터리  349,498,163,200 바이트 남음


In [14]:
my_iris=np.load('my_iris.npz')

In [15]:
xarr = my_iris['my_x']

In [16]:
xarr[:5]

array([[7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [6.5, 2.8, 4.6, 1.5],
       [6.3, 3.3, 4.7, 1.6]])