![차원](https://velog.velcdn.com/images%2Fmingki%2Fpost%2Fe0cdf6b1-cfd0-4a64-82d1-0c489237f1c2%2Farray_shape.png)




## ndarray 클래스

In [1]:
import numpy as np

In [2]:
xarr = np.array([23,45,56,76])
xarr

array([23, 45, 56, 76])

In [3]:
type(xarr)

numpy.ndarray

In [5]:
xarr.shape  # shape : 차원 출력 / 1차원, 요소 4개

(4,)

In [6]:
xarr.dtype  # dtype : 리스트 요소들의 타입 출력

# int32, int64, float32, float64

dtype('int32')

In [8]:
xarr.size  # 개수 출력
xarr.itemsize  # 비트수  출력

4

In [9]:
xarr.itemsize * xarr.size  # 메모리

16

In [13]:
yarr = np.array([[10,11],[12,13], [15,16]])
yarr.shape  # 요소 두 개짜리 리스트가 세 개

(3, 2)

In [14]:
yarr1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
yarr1.shape  # 요소 두 개짜리 리스트가 두 개 있고 채널이 세 개

(3, 2, 2)

In [15]:
yarr1

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [16]:
yarr1.dtype

dtype('int32')

In [18]:
# dtype 변경
yarr1 = yarr1.astype('float32')   # astype : dtype 변경
yarr1.dtype

# xarr = np.array([1,2,3,4], dtype='float')  # 생성할 때 dtype 설정

dtype('float32')

In [19]:
yarr = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
yarr.shape

(3, 2, 2)

In [25]:
# 차원 바꾸기
yarr = yarr.reshape(1,3,2,2)   # (-1,3,2,2) -> -1 : 차원을 추가할 때 최적의 차원으로 지정
yarr  # 축이 하나 더 생김 4차원 형태

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]]])

In [29]:
yarr = yarr.reshape(3,2,2)  # 다시 3차원으로 변환 = (-1,2,2)

In [24]:
yarr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
yarr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
yarr.shape

(3, 2, 2)

In [ ]:
# yarr.reshape(-1,3,2,2)
# yarr[np.newaxis, :]  # 맨 앞에 축 추가
# yarr[:, :, :, np.newaxis]  # 맨 뒤에 축 추가, 이건 아닌듯

In [33]:
xarr = np.arange(10).reshape(5,2)
xarr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [34]:
np.linspace(0,10,8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [36]:
np.full((2,3),0)

array([[0, 0, 0],
       [0, 0, 0]])

In [37]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
yarr.shape

(3, 2, 2)

In [40]:
# zeros_like()
np.zeros_like(yarr)  # yarr 차원과 맞추기 위한 함수

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [41]:
np.ones_like(yarr)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [45]:
# random : 난수 만드는 함수
# uniform(0, 10, 10) : 0~10에서 10개 뽑기
np.random.uniform(0,10, 10) 

array([5.883934  , 6.16909154, 4.23947026, 8.81038589, 5.75596305,
       3.4141853 , 3.65895543, 1.67792945, 8.36643231, 7.03016205])

In [46]:
# normal(a,b,n) : 평균 a, 표준편차 b인 정규분포에서 n개를 뽑겠다.
# 정규분포 안에서 난수를 생성, 평균에 가까운 난수가 나올 확률이 높음
np.random.normal(0,1,10) 

array([ 0.25791725,  0.64875984, -1.41832634,  1.49023367, -0.321681  ,
        0.4268443 ,  0.2452426 , -0.66073816, -1.32878473,  0.02435646])

In [48]:
# randn() : 표준 정규 분포(평균:0, 표준편차:1)에서 난수 생성 
np.random.randn(2,3)  # 표준 정규 분포에서 (2,3) 형태로 난수 생성

array([[-0.03689526, -0.20141432, -0.41194387],
       [-1.04805443,  0.95844289, -0.50614952]])

In [54]:
xarr = np.arange(0,12).reshape(3,4)
xarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
xarr.sum()  # 요소 전부를 합함

66

In [53]:
xarr.sum(axis=0)   # 0번째 축으로 계산

array([12, 15, 18, 21])

In [55]:
xarr.sum(axis=1)

array([ 6, 22, 38])

In [56]:
np.sum(xarr, axis=1)

array([ 6, 22, 38])

In [57]:
xarr.mean(axis=0)

array([4., 5., 6., 7.])

In [60]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,2],[3,4]])

print('같은 위치 곱 :', x*y)  # 같은 위치끼리 곱
print('행렬의 곱 :',x@y)  # 행렬의 곱

같은 위치 곱 : [[ 1  4]
 [ 9 16]]
행렬의 곱 : [[ 7 10]
 [15 22]]


In [62]:
np.dot(x,y)   # 내적, 행렬의 곱  

array([[ 7, 10],
       [15, 22]])

In [63]:
np.matmul(x,y)  # 매트릭스 곱, 행렬 곱만 실행

array([[ 7, 10],
       [15, 22]])

In [64]:
x = np.array([1,2,3])  
x>2  # 모든 요소 하나하나에 적용됨

array([False, False,  True])

In [65]:
x[[False, False,  True]]

# x[x>2]

array([3])

In [67]:
x[x>2] = -1
x

array([ 1,  2, -1])

In [70]:
# 두 개의 array 합치기
x = [1,2,3]
y = [4,5,6]

print(np.concatenate((x,y), axis=0))


[1 2 3 4 5 6]


In [75]:
# vstack, hstack
print("v : ", np.vstack((x,y)))
print("h : ",np.hstack((x,y)))

v :  [[1 2 3]
 [4 5 6]]
h :  [1 2 3 4 5 6]


In [77]:
x=[[1,2],[3,4]]
x[1][0]

3

In [78]:
x=np.array([[1,2],[3,4]])
x[1,0]

3

In [80]:
# where() : 조건에 맞는 인덱스 출력
x=np.array([1,2,3,4,5])
np.where(x>3)

(array([3, 4], dtype=int64),)

In [81]:
np.where(x>3, 1, 0)  # x>3이면 1, 작으면 0

array([0, 0, 0, 1, 1])

In [82]:
x=np.array([1,2,3,4,5,6])
x = np.where(x>3,1,0)
x.sum()

3

In [85]:
x = np.random.randn(4,3)
np.argmax(x, axis=1) # 각 row마다 최댓값을 가진 값의 인덱스를 출력

array([2, 1, 2, 2], dtype=int64)

In [86]:
xarr = np.array([1,2,3,4,5,6,7])
xarr

array([1, 2, 3, 4, 5, 6, 7])

In [89]:
print(xarr[0:5])
print(xarr[:-1])
print(xarr[-1])

[1 2 3 4 5]
[1 2 3 4 5 6]
7


In [90]:
y = xarr[3:5]
y

array([4, 5])

In [91]:
y[0]=5
y

array([5, 5])

In [92]:
xarr  # 원본도 값이 바뀜

array([1, 2, 3, 5, 5, 6, 7])

In [93]:
y=xarr[3:5].copy()
y

array([5, 5])

In [94]:
y[0]=-1
y

array([-1,  5])

In [95]:
xarr  # copy를 사용하면 원본은 바뀌지 않음

array([1, 2, 3, 5, 5, 6, 7])

### 파일 읽어오기


In [99]:
iris = np.genfromtxt('iris.csv', delimiter=',',skip_header=True)
iris[:5]

array([[5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan]])

In [129]:
xarr=iris[:,:-1]

xarr[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [127]:
# 0번째 열을 기준으로 5.8 보다 큰 행 출력
x = xarr[xarr[:,0] > 5.8,:]
x[:5]


array([[7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [6.5, 2.8, 4.6, 1.5],
       [6.3, 3.3, 4.7, 1.6]])

In [128]:
# 0번째 열을 기준으로 5.8보다 작은 행 출력
y = xarr[xarr[:,0]<=5.8,:]
y[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [131]:
# np.savez('my_iris.npz', my_x=x,my_y=y)  # 변수 저장해두기 
# my_iris = np.load('my_iris.npz')
# 저장할 때 키를 기억하고 있어야 함
# xarr = my_iris['my_x]

(80, 4)